
import java.awt.Cursor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.Timer;


/**
 *
 * @author Srinath.U
 */
public class ATM extends javax.swing.JFrame {

    /**
     * Creates new form ATM
     */
    public ATM() {
        initComponents();
        
        /*add placeholder style
        addPlaceholderStyle(t1);
        addPlaceholderStyle(passfield);*/
    }
      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        cb = new javax.swing.JCheckBox();
        login = new javax.swing.JButton();
        Forgotcode = new javax.swing.JButton();
        display = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        acnoE = new javax.swing.JLabel();
        passE = new javax.swing.JLabel();
        passfield = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 255));
        jLabel2.setText("Enter the Details");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 280, 80));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 204, 255));
        jLabel1.setText("Enter AC No:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 255));
        jLabel3.setText("PIN Code:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 140, 20));

        t1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        t1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                t1MouseMoved(evt);
            }
        });
        t1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t1FocusLost(evt);
            }
        });
        t1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t1KeyTyped(evt);
            }
        });
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 250, 220, -1));

        cb.setText("show password");
        cb.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                cbMouseMoved(evt);
            }
        });
        cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbActionPerformed(evt);
            }
        });
        getContentPane().add(cb, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 390, -1, -1));

        login.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        login.setText("Login");
        login.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                loginMouseMoved(evt);
            }
        });
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 440, -1, -1));

        Forgotcode.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Forgotcode.setText("Forgot  PIN Code");
        Forgotcode.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ForgotcodeMouseMoved(evt);
            }
        });
        Forgotcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ForgotcodeActionPerformed(evt);
            }
        });
        getContentPane().add(Forgotcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 580, -1, -1));

        display.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        getContentPane().add(display, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 500, 220, 20));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/acc.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 30, 50));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loc.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_Forgot_Password_50px_4.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 570, -1, -1));

        acnoE.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        acnoE.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(acnoE, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 210, 270, 20));

        passE.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        passE.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(passE, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 310, 280, 20));

        passfield.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        passfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passfieldFocusLost(evt);
            }
        });
        passfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passfieldActionPerformed(evt);
            }
        });
        passfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passfieldKeyTyped(evt);
            }
        });
        getContentPane().add(passfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 340, 220, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("New User");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 530, 170, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sky.jpeg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
           // TODO add your handling code here:*/
          if(t1.getText().trim().isEmpty() && passfield.getText().trim().isEmpty())
          {
              acnoE.setText("Enter the AC No*");
              passE.setText("Enter the PIN Code*");
          }
          else if(t1.getText().trim().isEmpty())
           {
               acnoE.setText("Enter the AC No*");
          }
          else if(passfield.getText().trim().isEmpty())
         {
             passE.setText("Enter the PIN Code*");
          }
          else
          {
              try
              {
                  Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/signup","root","root");
                  String sql="SELECT * FROM signup.data where AccountNumber=? and pincode=?";
                  PreparedStatement pst=con.prepareStatement(sql);
                  pst.setString(1, t1.getText());
                  pst.setString(2, passfield.getText());
                  ResultSet rs=pst.executeQuery();
                  if(rs.next())
                  {
                      JOptionPane.showMessageDialog(null,"CORRECT");
                      acnoE.setText("");
                      passE.setText("");
                      String x= t1.getText();
                      confirm c =new confirm(rs.getString(1),rs.getString(3),rs.getString(4),rs.getString(7),rs.getString(8),rs.getString(5),rs.getString(6));
                      c.setVisible(true);
                      dispose();
                  }
                  else
                  {
                      JOptionPane.showMessageDialog(null,"INCORRECT");
                      t1.setText("");
                      passfield.setText("");
                      acnoE.setText("");
                      passE.setText("");
                  }
                  con.close();
              }
              catch(Exception e)
              {
                  JOptionPane.showMessageDialog(null,e); 
              }
          }
    }//GEN-LAST:event_loginActionPerformed

    private void cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbActionPerformed
       if(cb.isSelected())
        {
            passfield.setEchoChar((char)0);
        }// TODO add your handling code here:
        else
        {
            passfield.setEchoChar('*');
        }
    }//GEN-LAST:event_cbActionPerformed

    private void t1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t1MouseMoved
        // TODO add your handling code here:
        //t1.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_t1MouseMoved

    private void cbMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbMouseMoved
        // TODO add your handling code here:
        cb.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));        
    }//GEN-LAST:event_cbMouseMoved

    private void loginMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseMoved
        // TODO add your handling code here:
        login.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
    }//GEN-LAST:event_loginMouseMoved

    private void ForgotcodeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ForgotcodeMouseMoved
        // TODO add your handling code here:
        Forgotcode.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_ForgotcodeMouseMoved

    private void ForgotcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ForgotcodeActionPerformed
        // TODO add your handling code here:
        dispose();
        Forgot forgot=new Forgot();
        forgot.show();
    }//GEN-LAST:event_ForgotcodeActionPerformed

    private void passfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passfieldActionPerformed

    private void t1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t1FocusGained
        // TODO add your handling code here:
        /*if(t1.getText().equals("Account Number"))
        {
            t1.setText(null);
            t1.requestFocus();
            removePlaceholderStyle1(t1);
        }*/
    }//GEN-LAST:event_t1FocusGained

    private void passfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passfieldFocusGained
        // TODO add your handling code here:
        /*if(passfield.getText().equals("PIN Code"))
        {
            passfield.setText(null);
            passfield.requestFocus();
            removePlaceholderStyle2(passfield);
        }*/
    }//GEN-LAST:event_passfieldFocusGained

    private void t1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t1FocusLost
        // TODO add your handling code here:
        /*if(t1.getText().length()==0)
        {
            addPlaceholderStyle(t1);
            t1.setText("Account Number");
        }*/
       if(Character.isAlphabetic(ch1))
        {
            acnoE.setText("Account number contains only 0-9*");
        }
        else
        {
            acnoE.setText("");
        }
       if(t1.getText().length()<6 || t1.getText().length()>6)
       {
           acnoE.setText("Enter Account Number of 6-Digits*");
       }
    }//GEN-LAST:event_t1FocusLost

    private void passfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passfieldFocusLost
        // TODO add your handling code here:
        /*if(passfield.getText().length()==0)
        {
            addPlaceholderStyle(passfield);
            passfield.setText("PIN Code");
            passfield.setEchoChar('\u0000');
        }*/
        if(Character.isAlphabetic(ch2))
        {
            passE.setText("PIN code contains only 0-9*");
        }
        else
        {
            passE.setText("");
        }
        if(passfield.getText().length()==0 || passfield.getText().length()>4 || passfield.getText().length()<4)
        {
            passE.setText("Set 4-digit PIN Code*");
        }
    }//GEN-LAST:event_passfieldFocusLost

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
       // this.requestFocusInWindow();
    }//GEN-LAST:event_formWindowGainedFocus

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        signup sp=new signup();
        sp.show();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    char ch1,ch2;
    private void t1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t1KeyTyped
        // TODO add your handling code here:
        ch1 =evt.getKeyChar();
        if(Character.isAlphabetic(ch1))
        {
            acnoE.setText("Account number consists of 0-9*");
        }
        else if(!Character.isDigit(ch1))
        {
        evt.consume();
        }
    }//GEN-LAST:event_t1KeyTyped

    private void passfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passfieldKeyTyped
        // TODO add your handling code here:
        ch2= evt.getKeyChar();
        if(Character.isAlphabetic(ch2))
        {
            passE.setText("PIN consists of 0-9*");
        }
        else if(!Character.isDigit(ch2))
        {
        evt.consume();
        }
    }//GEN-LAST:event_passfieldKeyTyped

    /*public void addPlaceholderStyle(JTextField textField)
    {
        Font font=textField.getFont();
        font=font.deriveFont(Font.TYPE1_FONT);
        textField.setFont(font);
        textField.setForeground(Color.GRAY);
    }
    
    public void removePlaceholderStyle1(JTextField textField)
    {
        Font font=textField.getFont();
        font=font.deriveFont(Font.PLAIN);
        textField.setFont(font);
        textField.setForeground(Color.black);
    }
    
    public void removePlaceholderStyle2(JPasswordField passwordField)
    {
        Font font=passwordField.getFont();
        font=font.deriveFont(Font.PLAIN);
        passwordField.setFont(font);
        passwordField.setForeground(Color.black);
    }*/
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ATM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Forgotcode;
    private javax.swing.JLabel acnoE;
    private javax.swing.JCheckBox cb;
    private javax.swing.JLabel display;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton login;
    private javax.swing.JLabel passE;
    private javax.swing.JPasswordField passfield;
    private javax.swing.JTextField t1;
    // End of variables declaration//GEN-END:variables
}
