
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Srinath.U
 */
public class signup extends javax.swing.JFrame {

    /**
     * Creates new form signup
     */
    public signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nametf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        phonenotf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dob = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        education = new javax.swing.JComboBox<>();
        occupationtf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        acnotf = new javax.swing.JTextField();
        pin = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        showpin = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        submitbutton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        nameE = new javax.swing.JLabel();
        pinE = new javax.swing.JLabel();
        accE = new javax.swing.JLabel();
        phE = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pin1 = new javax.swing.JPasswordField();
        disperror = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 255));
        jLabel1.setText("Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 123, 71, -1));

        nametf.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        nametf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nametfFocusLost(evt);
            }
        });
        nametf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nametfActionPerformed(evt);
            }
        });
        nametf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nametfKeyTyped(evt);
            }
        });
        getContentPane().add(nametf, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 171, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 255));
        jLabel2.setText("Phone Number");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        phonenotf.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        phonenotf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                phonenotfFocusLost(evt);
            }
        });
        phonenotf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                phonenotfKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phonenotfKeyTyped(evt);
            }
        });
        getContentPane().add(phonenotf, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 170, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 255));
        jLabel3.setText("DOB");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));
        getContentPane().add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 180, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 255));
        jLabel4.setText("Occupation");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, -1, -1));

        education.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        education.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "School Student", "UG", "PG", "Diploma", "PhD", "UNEDUCATED" }));
        getContentPane().add(education, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, 170, 30));

        occupationtf.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        getContentPane().add(occupationtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 170, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 255));
        jLabel5.setText("Education");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 255));
        jLabel6.setText("Account Number");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 120, -1, -1));

        acnotf.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        acnotf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                acnotfFocusLost(evt);
            }
        });
        acnotf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                acnotfKeyTyped(evt);
            }
        });
        getContentPane().add(acnotf, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 120, 250, -1));

        pin.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        pin.setToolTipText("");
        pin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pinFocusLost(evt);
            }
        });
        pin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pinKeyTyped(evt);
            }
        });
        getContentPane().add(pin, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 260, 250, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 255));
        jLabel7.setText("Confirm PIN Code");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 270, -1, -1));

        showpin.setText("show pincode");
        showpin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpinActionPerformed(evt);
            }
        });
        getContentPane().add(showpin, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 300, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 204, 255));
        jLabel8.setText("Address :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 340, -1, -1));

        address.setColumns(20);
        address.setRows(5);
        jScrollPane1.setViewportView(address);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 380, 430, 100));

        submitbutton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        submitbutton.setText("Submit");
        submitbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitbuttonMouseClicked(evt);
            }
        });
        submitbutton.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                submitbuttonComponentHidden(evt);
            }
        });
        submitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(submitbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 510, -1, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setText("Go Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 580, -1, -1));

        nameE.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        nameE.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(nameE, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 170, 20));

        pinE.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(pinE, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 240, 240, 20));

        accE.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(accE, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 100, 240, 20));

        phE.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        phE.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(phE, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 280, 20));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 204, 255));
        jLabel10.setText("Set PIN Code");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 200, -1, -1));

        pin1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        pin1.setToolTipText("");
        pin1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pin1FocusLost(evt);
            }
        });
        pin1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pin1KeyTyped(evt);
            }
        });
        getContentPane().add(pin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 190, 250, -1));

        disperror.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(disperror, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 170, 240, 20));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sky.jpeg"))); // NOI18N
        jLabel11.setText("jLabel4");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nametfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nametfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nametfActionPerformed

    private void submitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbuttonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_submitbuttonActionPerformed

    private void submitbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitbuttonMouseClicked
        // TODO add your handling code here:
        if(nametf.getText().isEmpty() || phonenotf.getText().isEmpty() || occupationtf.getText().isEmpty() || acnotf.getText().isEmpty() || pin.getText().isEmpty() || address.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Enter all the details");
        }
        else if(pin1.getText()!=pin.getText())
        {
            JOptionPane.showMessageDialog(null,"PIN Code doesn't match!");
            pin1.setText("");
            pin.setText("");
        }
        else
        {
            try
            {
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/signup","root","root");
                PreparedStatement st=con.prepareStatement("insert into data (AccountNumber, pincode, Name, DOB, Phone, Address, Education, Occupation, Balance)"+"values(?,?,?,?,?,?,?,?,?)");
                st.setInt(1, Integer.valueOf(acnotf.getText()));
                st.setInt(2, Integer.valueOf(pin.getText()));
                st.setString(3, nametf.getText());
                st.setString(4, dob.getDate().toString());
                st.setString(5, phonenotf.getText());
                st.setString(6, address.getText());
                st.setString(7, education.getSelectedItem().toString());
                st.setString(8, occupationtf.getText());
                st.setInt(9,0);
                st.execute();
                con.close();
                JOptionPane.showMessageDialog(null,"Account Created Successfully");
                ATM atm=new ATM();
                atm.show();
                dispose();
            }
            catch(SQLException e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_submitbuttonMouseClicked

    private void showpinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpinActionPerformed
        // TODO add your handling code here:
        if(showpin.isSelected())
        {
            pin.setEchoChar((char)0);
            pin1.setEchoChar((char)0);
        }// TODO add your handling code here:
        else
        {
            pin.setEchoChar('*');
            pin1.setEchoChar('*');
        }
    }//GEN-LAST:event_showpinActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ATM atm=new ATM();
        atm.show();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    char ch1,ch2,ch3,ch4,ch5;
    private void phonenotfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phonenotfKeyTyped
        // TODO add your handling code here:
        ch1 = evt.getKeyChar();
        if(Character.isAlphabetic(ch1))
        {
            phE.setText("Phone number contains only 0-9*");
        }
        else if(!Character.isDigit(ch1))
        {
            evt.consume();
        }
    }//GEN-LAST:event_phonenotfKeyTyped

    private void acnotfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_acnotfKeyTyped
        // TODO add your handling code here:
        ch2= evt.getKeyChar();
        if(Character.isAlphabetic(ch2))
        {
            accE.setText("Account number consists of 0-9*");
        }
        else if(!Character.isDigit(ch2))
        {
        evt.consume();
        }
    }//GEN-LAST:event_acnotfKeyTyped

    private void pinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pinKeyTyped
        // TODO add your handling code here:
        ch3= evt.getKeyChar();
        if(Character.isAlphabetic(ch3))
        {
            pinE.setText("PIN consists of 0-9*");
        }
        else if(!Character.isDigit(ch3))
        {
        evt.consume();
        }
    }//GEN-LAST:event_pinKeyTyped

    private void phonenotfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phonenotfKeyReleased
        // TODO add your handling code here:
       // phE.setText("");
    }//GEN-LAST:event_phonenotfKeyReleased

    private void phonenotfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phonenotfFocusLost
        // TODO add your handling code here:
        if(Character.isAlphabetic(ch1))
        {
            phE.setText("Phone number contains only 0-9*");
        }
        else
        {
            phE.setText("");
        }
        if(phonenotf.getText().length()==0 || phonenotf.getText().length() < 10 || phonenotf.getText().length() > 10)
        {
            phE.setText("Invalid Phone Number*");
        }
    }//GEN-LAST:event_phonenotfFocusLost

    private void acnotfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_acnotfFocusLost
        // TODO add your handling code here:
       if(Character.isAlphabetic(ch2))
        {
            accE.setText("Account number contains only 0-9*");
        }
        else
        {
            accE.setText("");
        }
       if(acnotf.getText().length()<6 || acnotf.getText().length()>6)
       {
           accE.setText("Set Account Number of 6-Digits*");
       }
    }//GEN-LAST:event_acnotfFocusLost

    private void pinFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pinFocusLost
        // TODO add your handling code here:
        if(Character.isAlphabetic(ch3))
        {
            pinE.setText("PIN code contains only 0-9*");
        }
        else
        {
            pinE.setText("");
        }
        if(pin.getText().length()>4 || pin.getText().length()<4)
        {
            pinE.setText("Set 4-digit PIN Code*");
        }
    }//GEN-LAST:event_pinFocusLost

    private void nametfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nametfKeyTyped
        // TODO add your handling code here:
        ch4 = evt.getKeyChar();
        if(Character.isDigit(ch4))
        {
            nameE.setText("Accepts only a-z / A-Z*");
        }
        else if(!Character.isAlphabetic(ch4))
        {
            evt.consume();
        }
    }//GEN-LAST:event_nametfKeyTyped

    private void nametfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nametfFocusLost
        // TODO add your handling code here:
        if(Character.isDigit(ch4))
        {
            nameE.setText("Accepts only a-z / A-Z*");
        }
        else
        {
            nameE.setText("");
        }
        if(nametf.getText().length()==0)
        {
            nameE.setText("Name field is empty");
        }
    }//GEN-LAST:event_nametfFocusLost

    private void submitbuttonComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_submitbuttonComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_submitbuttonComponentHidden

    private void pin1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pin1FocusLost
        // TODO add your handling code here:
         if(Character.isAlphabetic(ch5))
        {
            disperror.setText("PIN code contains only 0-9*");
        }
        else
        {
            disperror.setText("");
        }
        if(pin1.getText().length()>4 || pin1.getText().length()<4)
        {
            disperror.setText("Set 4-digit PIN Code*");
        }
    }//GEN-LAST:event_pin1FocusLost

    private void pin1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pin1KeyTyped
        // TODO add your handling code here:
        if(Character.isAlphabetic(ch5))
        {
            disperror.setText("PIN code contains only 0-9*");
        }
        else
        {
            disperror.setText("");
        }
        if(pin1.getText().length()>4 || pin1.getText().length()<4)
        {
            disperror.setText("Set 4-digit PIN Code*");
        }
    }//GEN-LAST:event_pin1KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accE;
    private javax.swing.JTextField acnotf;
    private javax.swing.JTextArea address;
    private javax.swing.JLabel disperror;
    private com.toedter.calendar.JDateChooser dob;
    private javax.swing.JComboBox<String> education;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameE;
    private javax.swing.JTextField nametf;
    private javax.swing.JTextField occupationtf;
    private javax.swing.JLabel phE;
    private javax.swing.JTextField phonenotf;
    private javax.swing.JPasswordField pin;
    private javax.swing.JPasswordField pin1;
    private javax.swing.JLabel pinE;
    private javax.swing.JCheckBox showpin;
    private javax.swing.JButton submitbutton;
    // End of variables declaration//GEN-END:variables
}
