
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Srinath.U
 */
public class transfer extends javax.swing.JFrame {

    /**
     * Creates new form transfer
     */
    public transfer() {
        initComponents();
    }
    
    String AccMyNum,Name;
    int bal;
    public transfer(String acc,String nam,int balance) {
    initComponents();
    AccMyNum=acc;
    Name=nam;
    nameDisplay.setText(Name);
    accDisp.setText(AccMyNum);
    int bal=balance;
    counterlabel.setText("02:00");
    Timer();
    timer.start();
    }

Timer timer;
int second=0,minute=2;
String ddSecond, ddMinute;
DecimalFormat dFormat=new DecimalFormat("00");
public void Timer()
    {
        timer =new Timer(1000,new ActionListener(){
            public void actionPerformed(ActionEvent e) {
                second--;
                ddSecond=dFormat.format(second);
                ddMinute=dFormat.format(minute);
                counterlabel.setText(ddMinute+" : "+ddSecond);
                if(second==-1)
                {
                    second=59;
                    minute--;
                    counterlabel.setText(ddMinute+" : "+ddSecond);
                }
                if(minute==0 && second==0)
                {
                    timer.stop();
                    JOptionPane.showMessageDialog(null,"Session Timed Out!!!");
                    dispose();
                    ATM t=new ATM();
                    t.setVisible(true);
                }
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        accDisp = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        accTf = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        nameDisplay = new javax.swing.JLabel();
        accE = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        counterlabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 255));
        jLabel1.setText("Make a Transfer");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 255));
        jLabel2.setText("To Account Number:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, -1, -1));

        accDisp.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        getContentPane().add(accDisp, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, 240, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 255));
        jLabel4.setText("From Account Number:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, -1, -1));

        accTf.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        accTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accTfActionPerformed(evt);
            }
        });
        getContentPane().add(accTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 350, 240, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setText("Proceed");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 440, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 204, 255));
        jLabel9.setText("Name:- ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, -1, -1));

        nameDisplay.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        nameDisplay.setToolTipText("");
        getContentPane().add(nameDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 220, 240, 30));

        accE.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        accE.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(accE, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 330, 240, 20));

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton4.setText("Go back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 540, -1, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timer50.png"))); // NOI18N
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 100, -1, 50));

        counterlabel.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        getContentPane().add(counterlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 100, 90, 50));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sky.jpeg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accTfActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String acc=accTf.getText();
        if(accTf.getText().trim().isEmpty())
        {
            accE.setText("Enter the receivers Account Number*");
        }
        else
        {
            try
            {
                  Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/signup","root","root");
                  Statement st=con.createStatement();
                  String sql="SELECT * FROM signup.data WHERE AccountNumber= ' "+ acc +" ' ";
                  ResultSet rs=st.executeQuery(sql);
                 if(rs.next())
                  {
                      accE.setText("");
                      confrimfund c =new confrimfund(rs.getString(1),rs.getString(3),rs.getString(4),rs.getString(7),rs.getString(8),rs.getString(5),rs.getString(6),AccMyNum,Name,rs.getInt(9));
                      c.setVisible(true);
                      dispose();
                      timer.stop();
                  }
                  else
                  {
                      accE.setText("");
                  }
                  con.close();
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        dispose();
        Transaction t =new Transaction(AccMyNum,Name);
        t.show();
        timer.stop();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transfer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accDisp;
    private javax.swing.JLabel accE;
    private javax.swing.JTextField accTf;
    private javax.swing.JLabel counterlabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel nameDisplay;
    // End of variables declaration//GEN-END:variables
}
